atlas:
  build: .
  ports:
    - "8000:8000"
  volumes:
    - .:/src
  links:
    - rethink
rethink:
  image: greyarch/rethinkdb
  expose: 
    - 28015
  ports:
    - "8080:8080"
  volumes_from:
    - dbData

# It is recommended to use a separate container for data volumes. 
# This provides some benefits, for e.g., the db container can be upgraded without affecting the data
dbData:
  image: busybox
  volumes:
    - ./docker/data:/data
  command: echo Data Volume for db